compatibility_date = "2026-01-22"
compatibility_flags = [ "nodejs_compat" ]

name = "github-actions-access-token"
main = "./index.ts"

preview_urls = false

[observability]
enabled = true

[vars]
GITHUB_APP_ID = "225539"
GITHUB_ACTIONS_TOKEN_ALLOWED_AUDIENCE ="github-actions-access-token.qoomon.workers.dev"
